# install-services.yml
---
  - hosts: all
    tasks:
      - name: Installing services
        yum:
          name: 
            - httpd
            - glib
            - jemalloc
            - rpm-devel
            - mod_ssl
          state: present
    
        