# install-services.yml
---
  - hosts: all
    tasks:
      - name: Installing services
        yum:
          name: 
            - httpd
            - glib
            - jemalloc
            - rpm-devel
            - mod_ssl
          state: present
      - name: Ensure group exists   
        group:
          name: jboss
          gid: 501
          name: apacheadmin
          gid: 502
          name: confgmgt
          gid : 503
          state: present
      
        