# users.yml
---
  - hosts: all
    vars:
      Repo: /appl
    tasks:
      - name: create directory
        file:
           path: /appl
           state: directory
      - name: Ensure group jboss exists 
        group:
          name: jboss
          gid: 501
          state: present
      - name: Ensure apacheadmin exists
        group:
          name: apacheadmin
          gid: 502
          state: present
      - name: Ensure confmgmt exists
        group:
          name: confgmgt
          gid: 503
          state: present
      - name: Add user "jboss" to the remote server
        user:
          name: jboss
          comment: "Privileged User"
          uid: 501
          group: jboss
          groups: confgmgt
      - name: Add user "apacheadmin" to the remote server
        user:
          name: apacheadmin
          comment: "Privileged User"
          uid: 502
          group: apacheadmin
          groups: confgmgt
     
      
